# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
