# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferSystem', '0002_auto_20170522_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
