# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferSystem', '0003_auto_20170523_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='location',
            field=models.CharField(choices=[('Living Room', 'Living Room'), ('Kids', 'Kids'), ('Bedrooms', 'Bedrooms'), ('Office Space', 'Office Space'), ('Kitchen', 'Kitchen')], max_length=2),
        ),
    ]
